apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pesync.fullname" . }}-daemonset-env
  namespace: {{ .Release.Namespace }}

data:
  RVBD_DSAPORT: {{ default "7074" .Values.env.pesync.RVBD_DSAPORT | quote }}
  METRIC_URL: {{ .Values.env.pesync.METRIC_URL | quote }}
  AUTH_TOKEN: {{ default "" .Values.env.pesync.AUTH_TOKEN | quote }}
  AUTH_TOKEN_PATH: {{ .Values.env.pesync.AUTH_TOKEN_PATH | quote }}
  API_NAME: {{ .Values.env.pesync.API_NAME | quote }}
  LABEL_MAPPINGS: {{ .Values.env.pesync.LABEL_MAPPINGS | quote }}
  DIMENSIONED_LABELS: {{ .Values.env.pesync.DIMENSIONED_LABELS | quote }}
